package main

import (
	"fmt"
	"log"
	"math/rand"
	"os"
	"strconv"
	"time"

	"github.com/darkvoice1/multi-tenant-saas-platform/backend/internal/config"
	"github.com/darkvoice1/multi-tenant-saas-platform/backend/internal/db"
	"github.com/darkvoice1/multi-tenant-saas-platform/backend/internal/models"
)

func main() {
	if _, err := os.Stat(".env"); err == nil {
		_ = config.LoadDotEnv(".env")
	}

	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config error: %v", err)
	}

	database, err := db.Connect(cfg)
	if err != nil {
		log.Fatalf("db error: %v", err)
	}

	slug := getEnv("FIXTURE_TENANT_SLUG", "demo")
	projectCount := getEnvInt("FIXTURE_PROJECTS", 2)
	taskCount := getEnvInt("FIXTURE_TASKS", 5)

	var tenant models.Tenant
	if err := database.Where("slug = ?", slug).First(&tenant).Error; err != nil {
		log.Fatalf("tenant not found: %v", err)
	}

	var user models.User
	if err := database.Where("tenant_id = ? AND role = ?", tenant.ID, "admin").First(&user).Error; err != nil {
		log.Fatalf("admin user not found: %v", err)
	}

	rand.Seed(time.Now().UnixNano())

	for i := 0; i < projectCount; i++ {
		project := models.Project{
			TenantID:    tenant.ID,
			Name:        fmt.Sprintf("Fixture Project %d", i+1),
			Description: "Generated by fixtures",
			CreatedBy:   &user.ID,
		}
		if err := database.Create(&project).Error; err != nil {
			log.Fatalf("create project: %v", err)
		}

		for j := 0; j < taskCount; j++ {
			status := randomStatus()
			due := time.Now().Add(time.Duration(24*(j+1)) * time.Hour)
			task := models.Task{
				TenantID:   tenant.ID,
				ProjectID:  project.ID,
				Title:      fmt.Sprintf("Task %d.%d", i+1, j+1),
				Status:     status,
				AssigneeID: &user.ID,
				Priority:   "medium",
				DueAt:      &due,
			}
			if err := database.Create(&task).Error; err != nil {
				log.Fatalf("create task: %v", err)
			}

			comment := models.TaskComment{
				TenantID: tenant.ID,
				TaskID:   task.ID,
				UserID:   user.ID,
				Content:  "Fixture comment",
			}
			_ = database.Create(&comment).Error

			if status == "review" {
				approval := models.TaskApproval{
					TenantID:   tenant.ID,
					TaskID:     task.ID,
					ApproverID: user.ID,
					Status:     "approved",
					Comment:    "Fixture approval",
				}
				_ = database.Create(&approval).Error
			}
		}
	}

	fmt.Printf("fixtures inserted for tenant %s\n", tenant.ID.String())
}

func randomStatus() string {
	statuses := []string{"todo", "in_progress", "review", "done"}
	return statuses[rand.Intn(len(statuses))]
}

func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func getEnvInt(key string, fallback int) int {
	if v := os.Getenv(key); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			return n
		}
	}
	return fallback
}
